/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "Uart.h"
#include "scheduler.h"
#include "led.h"
#include "Spi.h"
#include "Icm42688.h"
#include "NavTask.h"
#include "BringUp.h"

extern IfxCpu_syncEvent cpuSyncEvent;

static Scheduler_t g_sched;
static Led_t       g_led;

static void Task_LedToggle(void)
{
    Led_toggle(&g_led);
}

void core1_main(void)
{
    IfxCpu_enableInterrupts();
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 10u);

    Uart_println("CPU1 started");

    Led_init(&g_led, &MODULE_P20, 12u);

    /* Flight IMU on QSPI0 (T12, docs/REFACTORING_PLAN.md): moved here from
     * core0_main verbatim, along with NavTask_init(), so the QSPI ISR
     * retarget (Spi.c), the driver init and the task registration below all
     * land on the same core together -- an intermediate state with the ISR
     * on one core and the init on another does not fly (Risk 7 of the
     * refactor's predecessor step, T11, applies identically here). Nothing
     * shared with the I2C0 sensors, which stay on CPU0. */
    Spi_init();
    if (Icm42688_init() != FALSE)
    {
        Uart_print("ICM-42688-P detected (WHO_AM_I 0x47) in SPI mode ");
        Uart_printHexByte(Spi_getMode());
        Uart_println("");
    }
    else
    {
        uint8 who = 0u;

        Uart_println("ICM-42688-P not found");
        Spi_setMode(SPI_MODE_0);
        (void)Icm42688_readWhoAmI(&who);
        Uart_print("  WHO_AM_I mode0=");
        Uart_printHexByte(who);
        who = 0u;
        Spi_setMode(SPI_MODE_3);
        (void)Icm42688_readWhoAmI(&who);
        Uart_print("  mode3=");
        Uart_printHexByte(who);
        Uart_println("");
    }
    BringUp_dumpImu();     /* one-time ICM-42688-P register dump -- see BringUp.h */
    NavTask_init();         /* NavState_init, FusionCal_init, Ahrs_init, Fusion_init */

    Scheduler_init(&g_sched, &MODULE_STM1, 1u);
    Scheduler_addTask(&g_sched, Task_LedToggle, SCHED_MS(500u));
    (void)Scheduler_addTask(&g_sched, NavTask_step, SCHED_MS(20u));  /* 50 Hz IMU (QSPI0) */

    while (TRUE)
    {
        Scheduler_run(&g_sched);
    }
}
