/* GENERATED by tools/gen_a2l.py -- do not edit by hand.
 * Struct-offset guard, docs/MEMORY_PLACEMENT.md part 6: asserts the
 * compiler's own offsetof()/sizeof() for every field in every XCP block
 * agree with the layout this generator assumes when it writes
 * docs/AurixTricore.a2l. Regenerate after changing a struct:
 *     python tools/gen_a2l.py
 * CI runs 'python tools/gen_a2l.py --check' to catch a stale file, same as
 * the A2L itself.
 *
 * TASKING does not accept _Static_assert under this project's build flags
 * (confirmed by build) -- this uses the negative-array-size idiom instead,
 * with no C-side macro (see the generator for why). A failure here points
 * at the exact line, and because each array's own name embeds the block and
 * field, the exact field, whose real compiled offset stopped matching what
 * the generator assumed.
 *
 * Included by exactly one translation unit: src/bsw/LayoutAssert.c.
 */
#ifndef AURIXTRICORE_LAYOUT_ASSERT_GEN_H
#define AURIXTRICORE_LAYOUT_ASSERT_GEN_H

#include <stddef.h>

#include "Measurements.h"
#include "Diagnostics.h"
#include "Nvm.h"
#include "gpio.h"
#include "FusionCal.h"

/* Xcp_Data (Measurements.h) */
typedef char layout_assert_Xcp_Data_magic_offset[(offsetof(Xcp_Data, magic) == 0x0u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_verMajor_offset[(offsetof(Xcp_Data, verMajor) == 0x4u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_verMinor_offset[(offsetof(Xcp_Data, verMinor) == 0x5u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_verStep_offset[(offsetof(Xcp_Data, verStep) == 0x6u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_reserved_offset[(offsetof(Xcp_Data, reserved) == 0x7u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_tickMs_offset[(offsetof(Xcp_Data, tickMs) == 0x8u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_dieTempC_offset[(offsetof(Xcp_Data, dieTempC) == 0xCu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_dtscTempC_offset[(offsetof(Xcp_Data, dtscTempC) == 0x10u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_vddCore_offset[(offsetof(Xcp_Data, vddCore) == 0x14u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_vddp3_offset[(offsetof(Xcp_Data, vddp3) == 0x18u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_vext_offset[(offsetof(Xcp_Data, vext) == 0x1Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_rawVdd_offset[(offsetof(Xcp_Data, rawVdd) == 0x20u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_rawVddp3_offset[(offsetof(Xcp_Data, rawVddp3) == 0x21u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_rawVext_offset[(offsetof(Xcp_Data, rawVext) == 0x22u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_baroPresent_offset[(offsetof(Xcp_Data, baroPresent) == 0x23u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_diagStatus_offset[(offsetof(Xcp_Data, diagStatus) == 0x24u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_baroPressPa_offset[(offsetof(Xcp_Data, baroPressPa) == 0x28u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_baroTempC_offset[(offsetof(Xcp_Data, baroTempC) == 0x2Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_baroAltM_offset[(offsetof(Xcp_Data, baroAltM) == 0x30u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_imuPresent_offset[(offsetof(Xcp_Data, imuPresent) == 0x34u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_imuReserved_offset[(offsetof(Xcp_Data, imuReserved) == 0x35u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_accelX_offset[(offsetof(Xcp_Data, accelX) == 0x38u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_accelY_offset[(offsetof(Xcp_Data, accelY) == 0x3Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_accelZ_offset[(offsetof(Xcp_Data, accelZ) == 0x40u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gyroX_offset[(offsetof(Xcp_Data, gyroX) == 0x44u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gyroY_offset[(offsetof(Xcp_Data, gyroY) == 0x48u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gyroZ_offset[(offsetof(Xcp_Data, gyroZ) == 0x4Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_imuTempC_offset[(offsetof(Xcp_Data, imuTempC) == 0x50u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_coreExecUs_offset[(offsetof(Xcp_Data, coreExecUs) == 0x54u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_coreLoadPmil_offset[(offsetof(Xcp_Data, coreLoadPmil) == 0x6Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_coreAlive_offset[(offsetof(Xcp_Data, coreAlive) == 0x78u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_ethBytesPerSec_offset[(offsetof(Xcp_Data, ethBytesPerSec) == 0x84u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_ethUtilPmil_offset[(offsetof(Xcp_Data, ethUtilPmil) == 0x88u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_ethLinkMbits_offset[(offsetof(Xcp_Data, ethLinkMbits) == 0x8Au) ? 1 : -1];
typedef char layout_assert_Xcp_Data_magPresent_offset[(offsetof(Xcp_Data, magPresent) == 0x8Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_magReserved_offset[(offsetof(Xcp_Data, magReserved) == 0x8Du) ? 1 : -1];
typedef char layout_assert_Xcp_Data_magX_offset[(offsetof(Xcp_Data, magX) == 0x90u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_magY_offset[(offsetof(Xcp_Data, magY) == 0x94u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_magZ_offset[(offsetof(Xcp_Data, magZ) == 0x98u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_magFieldG_offset[(offsetof(Xcp_Data, magFieldG) == 0x9Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_magHeadingDeg_offset[(offsetof(Xcp_Data, magHeadingDeg) == 0xA0u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssPresent_offset[(offsetof(Xcp_Data, gnssPresent) == 0xA4u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssyear_offset[(offsetof(Xcp_Data, gnssyear) == 0xA6u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssmonth_offset[(offsetof(Xcp_Data, gnssmonth) == 0xA8u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssday_offset[(offsetof(Xcp_Data, gnssday) == 0xA9u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnsshour_offset[(offsetof(Xcp_Data, gnsshour) == 0xAAu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssmin_offset[(offsetof(Xcp_Data, gnssmin) == 0xABu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnsssec_offset[(offsetof(Xcp_Data, gnsssec) == 0xACu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssfixOk_offset[(offsetof(Xcp_Data, gnssfixOk) == 0xADu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnsstimeOk_offset[(offsetof(Xcp_Data, gnsstimeOk) == 0xAEu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssnavOk_offset[(offsetof(Xcp_Data, gnssnavOk) == 0xAFu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssrxBytes_offset[(offsetof(Xcp_Data, gnssrxBytes) == 0xB0u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnsssentences_offset[(offsetof(Xcp_Data, gnsssentences) == 0xB4u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnsserrors_offset[(offsetof(Xcp_Data, gnsserrors) == 0xB8u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssfixType_offset[(offsetof(Xcp_Data, gnssfixType) == 0xBAu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssnumSats_offset[(offsetof(Xcp_Data, gnssnumSats) == 0xBBu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnsslatDeg_offset[(offsetof(Xcp_Data, gnsslatDeg) == 0xBCu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnsslonDeg_offset[(offsetof(Xcp_Data, gnsslonDeg) == 0xC0u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssaltM_offset[(offsetof(Xcp_Data, gnssaltM) == 0xC4u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssspeedMps_offset[(offsetof(Xcp_Data, gnssspeedMps) == 0xC8u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssheadingDeg_offset[(offsetof(Xcp_Data, gnssheadingDeg) == 0xCCu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnsshAccM_offset[(offsetof(Xcp_Data, gnsshAccM) == 0xD0u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_gnssvAccM_offset[(offsetof(Xcp_Data, gnssvAccM) == 0xD4u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_fusionElapsed_offset[(offsetof(Xcp_Data, fusionElapsed) == 0xD8u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_a_D_offset[(offsetof(Xcp_Data, a_D) == 0xDCu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_a_v_d_offset[(offsetof(Xcp_Data, a_v_d) == 0xE0u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_a_d_offset[(offsetof(Xcp_Data, a_d) == 0xE4u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_fusionInnov_offset[(offsetof(Xcp_Data, fusionInnov) == 0xE8u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_fusionP00_offset[(offsetof(Xcp_Data, fusionP00) == 0xECu) ? 1 : -1];
typedef char layout_assert_Xcp_Data_fusionRejects_offset[(offsetof(Xcp_Data, fusionRejects) == 0xF0u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_fusionResets_offset[(offsetof(Xcp_Data, fusionResets) == 0xF4u) ? 1 : -1];
typedef char layout_assert_Xcp_Data_sizeof[(sizeof(Xcp_Data) == 0xF8u) ? 1 : -1];

/* Xcp_Cal (Diagnostics.h) */
typedef char layout_assert_Xcp_Cal_magic_offset[(offsetof(Xcp_Cal, magic) == 0x0u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_dtsMin_offset[(offsetof(Xcp_Cal, dtsMin) == 0x4u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_dtsMax_offset[(offsetof(Xcp_Cal, dtsMax) == 0x8u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_dtscMin_offset[(offsetof(Xcp_Cal, dtscMin) == 0xCu) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_dtscMax_offset[(offsetof(Xcp_Cal, dtscMax) == 0x10u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_vddMin_offset[(offsetof(Xcp_Cal, vddMin) == 0x14u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_vddMax_offset[(offsetof(Xcp_Cal, vddMax) == 0x18u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_vddp3Min_offset[(offsetof(Xcp_Cal, vddp3Min) == 0x1Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_vddp3Max_offset[(offsetof(Xcp_Cal, vddp3Max) == 0x20u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_vextMin_offset[(offsetof(Xcp_Cal, vextMin) == 0x24u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_vextMax_offset[(offsetof(Xcp_Cal, vextMax) == 0x28u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_tempDeltaMax_offset[(offsetof(Xcp_Cal, tempDeltaMax) == 0x2Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_debounceSec_offset[(offsetof(Xcp_Cal, debounceSec) == 0x30u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_fsVdd_offset[(offsetof(Xcp_Cal, fsVdd) == 0x34u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_fsVddp3_offset[(offsetof(Xcp_Cal, fsVddp3) == 0x38u) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_fsVext_offset[(offsetof(Xcp_Cal, fsVext) == 0x3Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Cal_sizeof[(sizeof(Xcp_Cal) == 0x40u) ? 1 : -1];

/* Xcp_Nvm (Nvm.h) */
typedef char layout_assert_Xcp_Nvm_magic_offset[(offsetof(Xcp_Nvm, magic) == 0x0u) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_command_offset[(offsetof(Xcp_Nvm, command) == 0x4u) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_userValue_offset[(offsetof(Xcp_Nvm, userValue) == 0x8u) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_seaLevelPa_offset[(offsetof(Xcp_Nvm, seaLevelPa) == 0xCu) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_magOffX_offset[(offsetof(Xcp_Nvm, magOffX) == 0x10u) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_magOffY_offset[(offsetof(Xcp_Nvm, magOffY) == 0x14u) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_magOffZ_offset[(offsetof(Xcp_Nvm, magOffZ) == 0x18u) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_magScaleX_offset[(offsetof(Xcp_Nvm, magScaleX) == 0x1Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_magScaleY_offset[(offsetof(Xcp_Nvm, magScaleY) == 0x20u) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_magScaleZ_offset[(offsetof(Xcp_Nvm, magScaleZ) == 0x24u) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_magDeclDeg_offset[(offsetof(Xcp_Nvm, magDeclDeg) == 0x28u) ? 1 : -1];
typedef char layout_assert_Xcp_Nvm_sizeof[(sizeof(Xcp_Nvm) == 0x2Cu) ? 1 : -1];

/* Xcp_Gpio (gpio.h) */
typedef char layout_assert_Xcp_Gpio_magic_offset[(offsetof(Xcp_Gpio, magic) == 0x0u) ? 1 : -1];
typedef char layout_assert_Xcp_Gpio_state_offset[(offsetof(Xcp_Gpio, state) == 0x4u) ? 1 : -1];
typedef char layout_assert_Xcp_Gpio_mode_offset[(offsetof(Xcp_Gpio, mode) == 0x14u) ? 1 : -1];
typedef char layout_assert_Xcp_Gpio_duty_offset[(offsetof(Xcp_Gpio, duty) == 0x24u) ? 1 : -1];
typedef char layout_assert_Xcp_Gpio_sizeof[(sizeof(Xcp_Gpio) == 0x34u) ? 1 : -1];

/* Xcp_Fusion (Measurements.h) */
typedef char layout_assert_Xcp_Fusion_magic_offset[(offsetof(Xcp_Fusion, magic) == 0x0u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_tickMs_offset[(offsetof(Xcp_Fusion, tickMs) == 0x4u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_rollDeg_offset[(offsetof(Xcp_Fusion, rollDeg) == 0x8u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_pitchDeg_offset[(offsetof(Xcp_Fusion, pitchDeg) == 0xCu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_yawDeg_offset[(offsetof(Xcp_Fusion, yawDeg) == 0x10u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_q_offset[(offsetof(Xcp_Fusion, q) == 0x14u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_rateDps_offset[(offsetof(Xcp_Fusion, rateDps) == 0x24u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_gyroBias_offset[(offsetof(Xcp_Fusion, gyroBias) == 0x30u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_accNed_offset[(offsetof(Xcp_Fusion, accNed) == 0x3Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_accMagG_offset[(offsetof(Xcp_Fusion, accMagG) == 0x48u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_magFieldG_offset[(offsetof(Xcp_Fusion, magFieldG) == 0x4Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_ahrsState_offset[(offsetof(Xcp_Fusion, ahrsState) == 0x50u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_accTrusted_offset[(offsetof(Xcp_Fusion, accTrusted) == 0x51u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_magTrusted_offset[(offsetof(Xcp_Fusion, magTrusted) == 0x52u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_reserved_offset[(offsetof(Xcp_Fusion, reserved) == 0x53u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_posD_offset[(offsetof(Xcp_Fusion, posD) == 0x54u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_velD_offset[(offsetof(Xcp_Fusion, velD) == 0x58u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_accBiasD_offset[(offsetof(Xcp_Fusion, accBiasD) == 0x5Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_baroBias_offset[(offsetof(Xcp_Fusion, baroBias) == 0x60u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_innovD_offset[(offsetof(Xcp_Fusion, innovD) == 0x64u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_varD_offset[(offsetof(Xcp_Fusion, varD) == 0x68u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_posN_offset[(offsetof(Xcp_Fusion, posN) == 0x6Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_posE_offset[(offsetof(Xcp_Fusion, posE) == 0x70u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_velN_offset[(offsetof(Xcp_Fusion, velN) == 0x74u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_velE_offset[(offsetof(Xcp_Fusion, velE) == 0x78u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_accBiasN_offset[(offsetof(Xcp_Fusion, accBiasN) == 0x7Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_accBiasE_offset[(offsetof(Xcp_Fusion, accBiasE) == 0x80u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_innovN_offset[(offsetof(Xcp_Fusion, innovN) == 0x84u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_innovE_offset[(offsetof(Xcp_Fusion, innovE) == 0x88u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_varN_offset[(offsetof(Xcp_Fusion, varN) == 0x8Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_originLatDeg_offset[(offsetof(Xcp_Fusion, originLatDeg) == 0x90u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_originLonDeg_offset[(offsetof(Xcp_Fusion, originLonDeg) == 0x94u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_originAltM_offset[(offsetof(Xcp_Fusion, originAltM) == 0x98u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_baroRejects_offset[(offsetof(Xcp_Fusion, baroRejects) == 0x9Cu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_baroResets_offset[(offsetof(Xcp_Fusion, baroResets) == 0xA0u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_gnssRejects_offset[(offsetof(Xcp_Fusion, gnssRejects) == 0xA4u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_gnssUpdates_offset[(offsetof(Xcp_Fusion, gnssUpdates) == 0xA8u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_verticalOk_offset[(offsetof(Xcp_Fusion, verticalOk) == 0xACu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_horizontalOk_offset[(offsetof(Xcp_Fusion, horizontalOk) == 0xADu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_originSet_offset[(offsetof(Xcp_Fusion, originSet) == 0xAEu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_reserved2_offset[(offsetof(Xcp_Fusion, reserved2) == 0xAFu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_covResets_offset[(offsetof(Xcp_Fusion, covResets) == 0xB0u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_gnssITow_offset[(offsetof(Xcp_Fusion, gnssITow) == 0xB4u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_gnssDupes_offset[(offsetof(Xcp_Fusion, gnssDupes) == 0xB8u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_ahrsBiasDegraded_offset[(offsetof(Xcp_Fusion, ahrsBiasDegraded) == 0xBCu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_reserved3_offset[(offsetof(Xcp_Fusion, reserved3) == 0xBDu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_phi_ist_offset[(offsetof(Xcp_Fusion, phi_ist) == 0xC0u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_om_ist_offset[(offsetof(Xcp_Fusion, om_ist) == 0xCCu) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_p_ned_ist_offset[(offsetof(Xcp_Fusion, p_ned_ist) == 0xD8u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_v_b_ist_offset[(offsetof(Xcp_Fusion, v_b_ist) == 0xE4u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_navDropped_offset[(offsetof(Xcp_Fusion, navDropped) == 0xF0u) ? 1 : -1];
typedef char layout_assert_Xcp_Fusion_sizeof[(sizeof(Xcp_Fusion) == 0xF4u) ? 1 : -1];

/* Xcp_FusionCal (FusionCal.h) */
typedef char layout_assert_Xcp_FusionCal_magic_offset[(offsetof(Xcp_FusionCal, magic) == 0x0u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_twoKpAcc_offset[(offsetof(Xcp_FusionCal, twoKpAcc) == 0x4u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_twoKpMag_offset[(offsetof(Xcp_FusionCal, twoKpMag) == 0x8u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_twoKi_offset[(offsetof(Xcp_FusionCal, twoKi) == 0xCu) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_sigmaAccD_offset[(offsetof(Xcp_FusionCal, sigmaAccD) == 0x10u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_sigmaBaro_offset[(offsetof(Xcp_FusionCal, sigmaBaro) == 0x14u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_sigmaBaroRw_offset[(offsetof(Xcp_FusionCal, sigmaBaroRw) == 0x18u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_tauBaroBias_offset[(offsetof(Xcp_FusionCal, tauBaroBias) == 0x1Cu) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_sigmaAccH_offset[(offsetof(Xcp_FusionCal, sigmaAccH) == 0x20u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_sigmaGnssVel_offset[(offsetof(Xcp_FusionCal, sigmaGnssVel) == 0x24u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_gnssPosRScale_offset[(offsetof(Xcp_FusionCal, gnssPosRScale) == 0x28u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_gateSigmaSq_offset[(offsetof(Xcp_FusionCal, gateSigmaSq) == 0x2Cu) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_gateMinM_offset[(offsetof(Xcp_FusionCal, gateMinM) == 0x30u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_reserved_offset[(offsetof(Xcp_FusionCal, reserved) == 0x34u) ? 1 : -1];
typedef char layout_assert_Xcp_FusionCal_sizeof[(sizeof(Xcp_FusionCal) == 0x40u) ? 1 : -1];

#endif /* AURIXTRICORE_LAYOUT_ASSERT_GEN_H */
