/**********************************************************************************************************************
 * \file Cpu4_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"
#include "IfxPort.h"
#include "IfxStm.h"
#include "Uart.h"

/* LED for CPU4 — borrows D306, Pin P20.11, active-low (shared with CPU0).
 * CPU0 guarantees its pin is HIGH (off) during phase 1. */
#define BLINKY_LED_PORT     &MODULE_P20
#define BLINKY_LED_PIN      11u
#define BLINKY_LED_ON       IfxPort_State_low
#define BLINKY_LED_OFF      IfxPort_State_high

extern IfxCpu_syncEvent cpuSyncEvent;
extern volatile uint32 g_ledPhase;  /* 0 = CPU0–3 active, 1 = CPU4–5 active */

void core4_main(void)
{
    uint32 i;

    IfxCpu_enableInterrupts();

    /* !!WATCHDOG4 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 10);

    Uart_println("CPU4 started");

    /* Pin already configured as output by CPU0; configure it here too so
     * CPU4 can also drive it safely when it borrows the LED in phase 1. */
    IfxPort_setPinMode(BLINKY_LED_PORT, BLINKY_LED_PIN,
                       IfxPort_Mode_outputPushPullGeneral);

    /* P20.11 is shared with CPU0 (which drives it during phase 0).
     * Rules: only write to the pin when we own it (phase 1).
     * In phase 0 just poll — any write would fight CPU0. */
    while(1)
    {
        if (g_ledPhase == 1u)
        {
            /* CPU4–5 window — flash ON for up to 500 ms, abort if phase flips */
            IfxPort_setPinState(BLINKY_LED_PORT, BLINKY_LED_PIN, BLINKY_LED_ON);
            for (i = 0u; i < 50u && g_ledPhase == 1u; i++)
                IfxStm_waitTicks(&MODULE_STM4, 1000000u);   /* 10 ms per sub-tick */
            /* Always write LED_OFF on exit: CPU0 waits a 20 ms grace period
             * before asserting ON, so this write lands safely before CPU0. */
            IfxPort_setPinState(BLINKY_LED_PORT, BLINKY_LED_PIN, BLINKY_LED_OFF);
        }
        else
        {
            /* Phase 0: CPU0 owns P20.11 — do NOT write to the pin; just poll */
            IfxStm_waitTicks(&MODULE_STM4, 1000000u);
        }
    }
}
