name: UNITTESTS

on:
  push:
    #branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:  # if commits getting staged and pipeline is not finished, it stops and only runs on the newest commit.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    name: C Unit tests
    runs-on: ubuntu-latest            # already includes ninja, therefore no installation needed
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit tests
        run: python3 tools/utest.py --clean
  sanitize:
    name: Sanitizers (ASan + UBSan)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Sanitize checks
        run: python3 tools/utest.py --sanitize