name: UNITTESTS

on:
  push:
    #branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unittests:
    name: C Unit tests
    runs-on: ubuntu-latest            # already includes ninja, therefore no installation needed
    steps:
      - uses: actions/checkout@v4
      - name: Run Unit tests
        run: python3 tools/utest.py